### ISSUE TITLE
Implement API for matching queue

### ISSUE THREAD

**Issue by chuabingquan** [MLH-Fellowship/0.3.2-team2-cross-pods#8]
To help users find three random cross-pod members to interact with, a global queue is needed on the server-side to serve that request.

The global queue should meet the following requirements:
1. It should enqueue all current logged-in (active) users
2. When an API call is made to get users to video call with, dequeue the first 3 people in the queue and send a common video chat URL to them via WebSockets ([Reverse engineer their video call API](https://videolink2me.com/))

**Comment by anshulrgoyal** [comment]
@chuabingquan I thinking polling would be easy to implement. We can shift it to websocket later.

**Comment by chuabingquan** [comment]
@anshulrgoyal Noted.
